import Head from "next/head";

export default function About () {
    return(
        <div>
            <Head>
                <title>Christian | Portfolio</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                About page
            </main>
      </div>
    )
}