import React from "react";
import Head from "next/head";

export default function Contact () {
    return(
        <div>
            <Head>
                <title>Christian | Project Page</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/logo.svg" />
            </Head>
            {/*  */}
            <main>
                <div>Contact Body</div>
            </main>
            {/*  */}
            <footer>
                <div>Contact Footer</div>
            </footer>
        </div>
    )
}