import React from "react";
import Head from "next/head";
import Header from "../components/Header";
import Footer from "../components/Footer";
import Image from "next/image";
import circle1 from "../public/circle1.png";
import circle2 from "../public/circle2.png";

export default function Hire () {
    return(
        <div>
            <Head>
                <title>Christian | Portfolio</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {/*  */}
            <Header />
            {/*  */}
            <main>
            <div className="h-12 w-12 pt-20">
                    <Image src={circle1} alt="circle" />
                </div>
                <div className="max-w-[80%] mx-auto font-metamorphous mt-32">
                    <h4 className="text-3xl font-poppins">Hello Recruiter,</h4>
                    <h1 className="text-7xl font-poppins mt-6">Good frontend dev tastes good</h1>
                    <h4 className="text-xl w-85% font-poppins font-light mt-6">
                        If you are here I strong believe we will be working closely or together as team soon.
                        Keep scrolling let me talk you through my journey so far.
                    </h4>
                </div>
                <div className="flex flex-row-reverse">
                    <div className="h-12 w-12 mt-4">
                    <Image src={circle2} alt="circle" />
                    </div>
                </div>
                {/*  */}
                <div className="max-w-[80%] mx-auto mt-32 font-metamorphous">
                    <h1 className="text-7xl font-light mb-10">Hire Me</h1>
                    <div className="mt-10 bg-white w-full h-auto pt-10 pb-20 font-poppins">
                        <div className="max-w-[80%] mx-auto">
                            <h1 className="text-2xl">Dear <span className="text-corered">Recruiter</span>,</h1>
                            <p className="text-sm mt-3 text-gray-600">Please fill the form, will respones with 24hours.</p>
                            <form className="space-y-5">
                                <div className="mt-8">
                                    <label className="text-sm">{`Recruiter's Name`}</label>
                                    <input className="border w-full h-10 rounded outline-none focus:border-inherit px-3 text-sm" type="text" />
                                </div>
                                <div>
                                    <label className="text-sm">{`Company's Name`} </label>
                                    <input className="border w-full h-10 rounded outline-none focus:border-inherit px-3 text-sm" type="text" />
                                </div>
                                <div>
                                    <label className="text-sm">{`Job Type`} </label>
                                    <select className="border w-full h-10 rounded outline-none focus:border-inherit px-3 text-sm">
                                        <option value="contract">Contract</option>
                                        <option value="partTime">Part-Time</option>
                                        <option value="contract">Full-Time</option>
                                    </select>
                                </div>
                                <div>
                                    <label className="text-sm">{`Description`} </label>
                                    <textarea className="border w-full h-32 rounded outline-none focus:border-inherit p-3" />
                                </div>
                                <button className="bg-corered text-white mt-5 w-full py-3 rounded">Send</button>
                            </form>
                        </div>
                    </div>
                </div>
            </main>
            {/*  */}
            <footer>
                <Footer />
            </footer>
      </div>
    )
}