import React from 'react';
import Head from 'next/head';
import Image from 'next/image';
import Logo from "../public/logo.svg";
import Circle1 from "../public/circle1.png";
import Circle2 from "../public/circle2.png";
import Rainbow from "../public/rainbow.png";
import {BsFillMoonStarsFill} from "react-icons/bs";
import {FaFacebookF, FaTwitter, FaLinkedinIn, FaGithubAlt} from "react-icons/fa";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Christian | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
      </Head>

      <header className="h-20 border">
        <div className="flex justify-between items-center max-w-[90%] mx-auto h-full">
          <div className="flex items-center">
            <Image src={Logo} alt="logo" />
          </div>
          <div className="flex">
            <nav className="mr-20">
              <ul className="flex space-x-10">
                <li className="text-primaryred"><a href='#'>#Home</a></li>
                <li><a href='#'>#About</a></li>
                <li><a href='#'>#Resume</a></li>
                <li><a href='#'>#Project</a></li>
                <li><a href='#'>#Contact</a></li>
              </ul>
            </nav>
            <button>
              <BsFillMoonStarsFill />
          </button>
          </div>
        </div>
      </header>
      {/*  */}
      <main>
        <div className="h-12 w-12">
          <Image src={Circle1} alt="circle" />
        </div>
        <div className="h-12 w-12 fixed right-0 bottom-32">
          <Image src={Circle2} alt="circle" />
        </div>
        {/*  */}
        <div className="max-w-[70%] mx-auto">
          <div className="h-20 w-20 mb-5">
            <Image src={Rainbow} alt="rainbow" />
          </div>
          <div className="text-center font-metamorphous">
            <h4 className="text-3xl">Hello world,</h4>
            <h1 className="text-7xl my-4">{`I'm Christian Chiemela`}</h1>
            <h4 className="text-2xl font-light mt-6">a frontend engineer, specialist in javascript.</h4>
            <div className="flex justify-center space-x-7 mt-10">
              <span className="bg-coreblue rounded-full p-2">
                <FaFacebookF />
              </span>
              <span className="bg-coreblue rounded-full p-2">
                <FaTwitter />
              </span>
              <span className="bg-coreblue rounded-full p-2">
                <FaLinkedinIn />
              </span>
              <span className="bg-coreblue rounded-full p-2">
                <FaGithubAlt />
              </span>
            </div>
          </div>
          <div className="flex flex-row-reverse mt-10">
            <div className="h-20 w-20">
              <Image className="flex flex-row-reverse" src={Rainbow} alt="rainbow" />
            </div>
          </div>
        </div>
      </main>
      {/*  */}
      <footer>
          <p className="fixed bottom-6 w-full text-center font-metamorphous">Copyright © 2022 designed by Christian Chiemela All rights reserved.</p>
      </footer>
    </div>
  )
}
