import React from 'react';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import Circle1 from "../public/circle1.png";
import Circle2 from "../public/circle2.png";
import Rainbow from "../public/rainbow.png";
import Header from '../components/Header';
import socialNavs from '../components/Nav/socialNavs';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Christian | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo1.svg" />
      </Head>
      {/*  */}
      <Header />
      {/*  */}
      <main>
        <div className="h-12 w-12 pt-16">
          <Image src={Circle1} alt="circle" />
        </div>
        <div className="h-12 w-12 fixed right-0 bottom-32">
          <Image src={Circle2} alt="circle" />
        </div>
        {/*  */}
        <div className="max-w-[70%] mx-auto pt-10">
          <div className="h-20 w-20 mb-5">
            <Image src={Rainbow} alt="rainbow" />
          </div>
          <div className=" font-poppins mt-14">
            <h4 className="text-3xl">Hello Recruiter,</h4>
            <h1 className="text-7xl font-metamorphous my-4">{`I'm Christian Chiemela`}</h1>
            <h4 className="text-xl font-light mt-6 w-85%">a frontend engineer, specialist in javascript. Love Building amazing things with <span className="text-corered font-metamorphous">ReactJs</span> and <span className="text-corered font-metamorphous">Typescript</span>.</h4>
            <div className="flex space-x-7 mt-7">
              {socialNavs?.map((socialNav, index) => (
                <Link key={index} href={socialNav.url}>
                  <span className="bg-coreblue cursor-pointer rounded-full h-7 flex justify-center items-center w-7">
                    {socialNav.icon} 
                  </span>
                </Link>
              ))}
            </div>
          </div>
          <div className="flex flex-row-reverse mt-10">
            <div className="h-20 w-20">
              <Image className="flex flex-row-reverse" src={Rainbow} alt="rainbow" />
            </div>
          </div>
        </div>
      </main>
      {/*  */}
      <footer>
          <p className="fixed bottom-6 w-full text-center font-metamorphous">Copyright © 2022 designed by Christian Chiemela All rights reserved.</p>
      </footer>
    </div>
  )
}
