import React from "react";
import Head from "next/head";
import Header from "../components/Header";

export default function Project () {
    return(
        <div>
            <Head>
                <title>Christian | Project Page</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/logo.svg" />
            </Head>
            {/*  */}
            <Header />
            {/*  */}
            <main>
                <div>Body</div>
            </main>
            {/*  */}
            <footer>
                <div>Footer</div>
            </footer>
        </div>
    )
}